version: "3.8"

volumes:
  dbdata:

services:
  # Database
  database:
    # image: mariadb:10.7
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    # - ./docker/database/my.cnf:/etc/mysql/conf.d/custom.cnf
    command: --default-authentication-plugin=mysql_native_password
    # restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      # - MYSQL_USER=${DB_USERNAME}
      # - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  # formerly phpmyadmin
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
